package zhrk.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQxDisUser<M extends BaseQxDisUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("ID", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public M setUserid(java.lang.Integer userid) {
		set("USERID", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("USERID");
	}

	public M setDisid(java.lang.Integer disid) {
		set("DISID", disid);
		return (M)this;
	}
	
	public java.lang.Integer getDisid() {
		return getInt("DISID");
	}

}
